{
 "title": "Global",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nat_host",
    "label": "nat_host:",
    "query": "label_values(up{job=~\"pfsense.*\",instance=~\".+\"}, instance)"
   },
   {
    "name": "nat_port",
    "label": "nat_port",
    "query": "label_values(up{job=~\"pfsense.*\"}, instance)"
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" },
   {
    "name": "mountpoint",
    "label": "mountpoint",
    "query": "label_values(node_filesystem_size_bytes{instance=~\"$instance:$port\"}, mountpoint)"
   },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster_name)" },
   {
    "name": "esxi_host",
    "label": "esxi_host",
    "query": "label_values(vmware_host_boot_timestamp_seconds{cluster_name=~\"$cluster\"},host_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "table-old",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(vmware_vm_power_state{cluster_name=\"$cluster\"})",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(vmware_vm_cpu_usagemhz_average/vmware_vm_max_cpu_usage{cluster_name=\"$cluster\"}*100)",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(vmware_vm_mem_active_average/vmware_vm_memory_max{cluster_name=\"$cluster\"}/10)",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "RAID status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "raid_status", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "NAT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Busy",
   "type": "bargauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$nat_host:$nat_port\"}[30s])) / count(count(node_cpu_seconds_total{instance=~\"$nat_host:$nat_port\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Network Traffic / sec",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$nat_host:$nat_port\"}[$interval]) * 8 > 0",
     "legendFormat": "{{device}} recv"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"62.210.117.84:9100\"}[$interval]) * 8 > 0",
     "legendFormat": "{{device}} trans"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_active_bytes{instance=~\"$nat_host:$nat_port\"} + node_memory_wired_bytes{instance=~\"$nat_host:$nat_port\"}) / node_memory_size_bytes{instance=~\"$nat_host:$nat_port\"}) * 100"
    }
   ]
  },
  {
   "title": "Load Average (5m)",
   "type": "bargauge",
   "description": "LA / CPU count (5 min average)",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=~\"$nat_host:$nat_port\"} / scalar(count(count(node_cpu_seconds_total{instance=~\"$nat_host:$nat_port\"}) by (cpu)))"
    }
   ]
  },
  { "title": "ESXi $esxi_host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "esxi_host" },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usagemhz_average{host_name=~\"$esxi_host\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxi_host\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxi_host\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxi_host\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_net_usage_average{host_name=~\"$esxi_host\"}",
     "legendFormat": "Total Usage"
    }
   ]
  },
  {
   "title": "Cpu",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 13 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_num_cpu{host_name=~\"$esxi_host\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 13 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vmware_host_memory_max{host_name=~\"$esxi_host\"})"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-vmware_host_boot_timestamp_seconds{host_name=~\"$esxi_host\"} "
    }
   ]
  },
  { "title": "ESXi $esxi_host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usagemhz_average{host_name=~\"$esxi_host\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxi_host\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxi_host\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxi_host\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_net_usage_average{host_name=~\"$esxi_host\"}",
     "legendFormat": "Total Usage"
    }
   ]
  },
  {
   "title": "Cpu",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 16 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_num_cpu{host_name=~\"$esxi_host\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 16 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vmware_host_memory_max{host_name=~\"$esxi_host\"})"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 16 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-vmware_host_boot_timestamp_seconds{host_name=~\"$esxi_host\"} "
    }
   ]
  },
  { "title": "VEEAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"runningbackups\") FROM \"veeamstats\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"successfulbackups\") FROM \"veeamstats\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warning",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"warningbackups\") FROM \"veeamstats\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"failedbackups\") FROM \"veeamstats\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT distinct(\"REPO_nas-bocal\") FROM \"veeamstats\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}