{
 "title": "VMs status",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nat_instance",
    "label": "nat_host:",
    "query": "label_values(up{job=~\"pfsense.*\",instance=~\".+\"}, instance)"
   },
   {
    "name": "nat_port",
    "label": "nat_port",
    "query": "label_values(up{job=~\"pfsense.*\"}, instance)"
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" },
   {
    "name": "mountpoint",
    "label": "mountpoint",
    "query": "label_values(node_filesystem_size_bytes{instance=~\"$instance:$port\"}, mountpoint)"
   },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster_name)" },
   {
    "name": "esxi_host",
    "label": "esxi_host",
    "query": "label_values(vmware_host_boot_timestamp_seconds{cluster_name=~\"$cluster\"},host_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Power State",
   "type": "table-old",
   "gridPos": { "h": 20, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(vmware_vm_power_state{cluster_name=\"$cluster\"})",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table-old",
   "gridPos": { "h": 20, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(vmware_vm_cpu_usagemhz_average/vmware_vm_max_cpu_usage{cluster_name=\"$cluster\"}*100)",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "table-old",
   "gridPos": { "h": 20, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(vmware_vm_mem_usage_average/vmware_vm_memory_max{cluster_name=\"$cluster\"}*100)",
     "legendFormat": "{{vm_name}}"
    }
   ]
  }
 ]
}