{
 "title": "Alerting",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "iDRAC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redfish_exporter_general_health{job=\"idrac-name\"}"
    }
   ]
  },
  {
   "title": "Power status alert",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redfish_exporter_general_status{job=\"idrac-name\"}"
    }
   ]
  },
  {
   "title": "Power state alert",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redfish_exporter_power{job=\"idrac-name\"}"
    }
   ]
  },
  {
   "title": "Fans redundancy state alert",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redfish_exporter_power{job=\"idrac-name\"}"
    }
   ]
  },
  {
   "title": "Disk with errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(redfish_exporter_disk{job=\"idrac-name\"} < 2) or vector(0)"
    },
    {
     "expr": "count(redfish_exporter_disk{job=\"idrac-2\"} < 2) or vector(0)"
    }
   ]
  },
  {
   "title": "Fans with errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(redfish_exporter_fan{job=\"idrac-name\"} < 2) or vector(0)"
    }
   ]
  },
  {
   "title": "Power Supply with errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(redfish_exporter_power_supply{job=\"idrac-name\"} < 2) or vector(0)"
    }
   ]
  },
  { "title": "VEEAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } }
 ]
}