{
 "title": "Redfish exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(exported_job)" }
  ]
 },
 "panels": [
  { "title": "iDRAC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Power comsumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "redfish_exporter_power_comsumption{exported_job=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_power_info{exported_job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Tag version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_general_info{exported_job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "General State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_general_state{exported_job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "redfish_exporter_thermal_location{exported_job=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "General Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_general_health{exported_job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Tag version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_general_info{exported_job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "General Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_general_status{exported_job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk states / health",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "redfish_exporter_disk{exported_job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "redfish_exporter_fan{type=\"rpm\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperatures (degres)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "redfish_exporter_thermal_location{exported_job=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power comsumption",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redfish_exporter_power_comsumption{exported_job=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}