{
 "title": "Veeam",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running Backups",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "runningbackups" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful Backups",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "successfulbackups" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warning Backups",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "warningbackups" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Backups",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "failedbackups" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Repository Free Space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "REPO_Backup_datastore" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backup Read/Transfer",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "totalbackupread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "backupread" ], "type": "alias" }
      ],
      [
       { "params": [ "totalbackupread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "backuptransfer" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Backups",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "runningbackups" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successfull Backups",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "successfulbackups" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warning Backups",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "warningbackups" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Backups",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "failedbackups" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "- 16000000000" ], "type": "math" },
       { "params": [ "available_bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DESKTOP-2O6EPOJ" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Processor Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DESKTOP-2O6EPOJ" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       { "params": [ "bytes_received" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       { "params": [ "bytes_sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "DESKTOP-2O6EPOJ" }
     ]
    }
   ]
  }
 ]
}