{
 "title": "VMware Clusters",
 "description": "VMware ESXi single instance graphs.",
 "tags": [ "vmware" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster_name)" }
  ]
 },
 "panels": [
  {
   "title": "Cpu Core Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_num_cpu{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cpu Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_max{cluster_name=~\"$cluster\"}) "
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_max{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Host Number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_host_connection_state{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Host In Maintenance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_host_maintenance_mode{cluster_name=~\"$cluster\"}==1) OR vector(0)"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_usagemhz_average{cluster_name=~\"$cluster\"}) * 100 / sum(vmware_host_cpu_max{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }"
    }
   ]
  },
  {
   "title": "Max VM Cpu Ready on Cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vmware_vm_cpu_ready_summation{cluster_name=~\"$cluster\"})/ 200",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Max VM Cpu Co-Stop on Cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vmware_vm_cpu_costop_summation{cluster_name=~\"$cluster\"})/200",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_usagemhz_average{cluster_name=~\"$cluster\"}) * 100 / sum(vmware_host_cpu_max{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_usage{cluster_name=~\"$cluster\"}) * 100 / sum(vmware_host_memory_max{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Max VM Ballooning",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(vmware_vm_mem_vmmemctl_average{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Max VM Swapped",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(vmware_vm_mem_swapped_average{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_host_memory_usage{cluster_name=~\"$cluster\"}) * 100) / sum(vmware_host_memory_max{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_net_received_average{cluster_name=~\"$cluster\"})+sum(vmware_vm_net_transmitted_average{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Network Receive Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_net_received_average{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Network Transmit Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_net_transmitted_average{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster}}"
    }
   ]
  },
  {
   "title": "Cluster Network Broadcast RX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_net_broadcastRx_summation{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Network Broadcast TX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_net_broadcastTx_summation{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster}}"
    }
   ]
  },
  {
   "title": "Host Network Multicast RX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_net_multicastRx_summation{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Network Multicast TX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_net_multicastTx_summation{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Disk Read And Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_disk_read_average{cluster_name=~\"$cluster\"})+sum(vmware_vm_disk_write_average{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Disk Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_disk_read_average{cluster_name =~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Disk Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vm_disk_write_average{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  }
 ]
}